"""removed length restriction for hashed password

Revision ID: 4268284faaf5
Revises: 73a47fcd11d4
Create Date: 2024-12-07 21:29:12.012287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4268284faaf5'
down_revision: Union[str, None] = '73a47fcd11d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
